Prefix:
  prefix: '&5&lZitroplay.eu &7|'
  noperm: '&5&lZitroplay.eu &7| &cDu hast keine Permissions um dies zu nutzen!'
Errors:
  console: '&4Du kannst diesen Befehl nicht in der Console nutzen!'
  playernotfound: '&5&lZitroplay.eu &7| &cDer Spieler wurde nicht gefunden oder ist offline'
Join:
  notplayedbefore: '&6Willkommen &b'
  title: '&6Willkommen zurück &b'
  subtitle: '&7auf &5&lZitroplay.eu'
Scoreboard:
  prefix: '&f&lZ&b&li&f&lt&b&lr&f&lo&b&lp&f&ll&b&la&f&ly&b&l.&f&le&b&lu '
  score14: '&9'
  score13: '&f&l✪ &7&lR&f&la&7&ln&f&lg&7&l:'
  score12: '&2'
  score11: '&8'
  score10: '&e&l₿ &f&lC&e&lo&f&li&e&ln&f&ls&e&l:'
  score9: '&4'
  score8: '&7'
  score7: '&c&l۞ &f&lR&c&lu&f&lb&c&ly&f&l:'
  score6: '&3'
  score5: '&6'
  score4: '&f&l♣ &7&lC&f&ll&7&la&f&ln&7&l:'
  score3: '&1'
  score2: '&5'
  score1: '&c&l♥ &f&lS&c&lo&f&lc&c&li&f&la&c&ll&f&l:'
  score0: '&7➪ &d/dc'
  coinsteam: 'coins'
  coinsentry: '&4'
  coinsprefix: '&7➪&6'
  tallerteam: 'taller'
  tallerentry: '&3'
  tallerprefix: '&7➪&c'
  rangteam: 'rang'
  rangentry: '&2'
  rangprefix: '&7➪ &d'
  clanteam: 'clan'
  noclan: '&7➪ &eKein Clan'
  clanentry: '&1'
  clanprefix: '&7➪&e'
FarmWelt:
  farmwelt: 'Farmwelt2'
  nether: 'nether'
  end: 'end'
DailyRewards:
  invprefix: '&6&lDailyRewards'
  prefix: '&8[&6DailyRewards&8]'
Coins:
  topten: '&7&m==========&r &b&lCoins Top &7&m=========='
  prefix: '&5Coins'
Taller:
  topten: '&7&m==========&r &b&lTaller Top &7&m=========='
  prefix: '&5Taller'
GlobalMute:
  prefix: '&7==================&8[&5GlobalMute&8]&7=================='
CommandSpy:
  prefix: '&7[&bCommandSpy&7] &8'
Clan:
  clanchatprefix: '&8[&2Clan-Chat&8] &2'
  prefix: '&3ClanSystem &7|'
Ban:
  banprefix: '&8[&2&5&lZitroplay.eu&8] &2'
  prefix: '&3BanSystem &7|'
  banlist: '&7&m==========&r&8[&5&lBan-Liste&8]&7&m=========='
  baninfo: '&7&m==========&r&8[&5&lBan-Info&8]&7&m=========='
  muteinfo: '&7&m==========&r&8[&5&lMute-Info&8]&7&m=========='
  mutelist: '&7&m==========&r&8[&5&lMute-Liste&8]&7&m=========='
Msg:
  msgsent: '&f-> &aMIR &7»&f'
  msgme: '&6ICH &f-> &a'
  prefix: '&7[MSG]'
Rankup:
  prefix: '&7[Rankup]'
  helpheader: '"&7&m==========&r&8[&b&lRankup Hilfe&8]&7&m=========="'
RankShop:
  vip: '&0VIP'
  premium: '&6Premium'
  zaltur: '&aZaltur'
  mega: '&c&lMEGA'
  kami: '&b&lK&f&la&b&lm&f&li'
  oni: '&c&lO&f&ln&c&li'
  rangshop: '&6&lRang Shop'
Particel:
  fire: '&cFeuer-Partikel'
  heart: '&cHerzen-Partikel'
  water: '&bWasser-Partikel'
  totem: '&aTotem-Partikel'
  music: '&5Musik-Partikel'
  slime: '&aSlime-Partikel'
  angry: '&cAngry-Partikel'
  lava: '&4Lava-Partikel'
  money: '&2Geld-Partikel'
  diamond: '&bDiamond-Partikel'
  redstone: '&cRedstone-Partikel'
  koral: '&dKoralen-Partikel'
  cookie: '&6Kekse-Partikel'
  effectsremove: '&cEffekt entfernen'
  effectinv: '&6&lEffekte Menü'
Shop:
  sellshopprefix: '&c&lVerkaufen'
  breakstuffinvprefix: '&6&lAbbaubares'
  erzstuffinvprefix: '&6&lErz'
  farmerstuffinvprefix: '&6&lFarmer'
  fishstuffinvprefix: '&6&lFisch'
  lightstuffinvprefix: '&6&lBeleuchtung'
  logstuffinvprefix: '&6&lStämme'
  moblootinvprefix: '&6&lMobloot'
  plantsinvprefix: '&6&lPflanzen'
  rarestuffinvprefix: '&6&lSeltenes'
  shovelstuffinvprefix: '&6&lSchaufelbares'
  buyshopprefix: '&6&lAdmin Shop'
  spawnegginvprefix: '&c&lSpawn-Eggs'
  specialinvprefix: '&3&lSpezielles'
BackPack:
  prefix: '&cBackpack &8x &6'
Permissions:
  rename: 'sp.rename'
  addlore: 'sp.addlore'
  removelore: 'sp.removelore'
  prtp: 'sp.prtp'
  rtp: 'sp.rtp'
  particelremove: 'sp.particleremove'
  cookieparticel: 'sp.cookie'
  coralparticel: 'sp.coral'
  redstoneparticel: 'sp.redstone'
  diamondparticel: 'sp.diamond'
  moneyparticel: 'sp.money'
  lavaparticel: 'sp.lava'
  angryparticel: 'sp.angry'
  slimeparticel: 'sp.slime'
  musicparticel: 'sp.music'
  totemparticel: 'sp.totem'
  waterparticel: 'sp.water'
  heartparticel: 'sp.heart'
  fireparticel: 'sp.fire'
  backpackedit: 'sp.editbackpacks'
  backpackother: 'sp.backpack.others'
  rangshop: 'sp.rangshop'
  addtaller: 'sp.addtaller'
  removetaller: 'sp.removetaller'
  settaller: 'sp.settaller'
  removeteamtaller: 'sp.removeteamtaller'
  premium: 'sp.premium'
  editinv: 'sp.editinv'
  addrankup: 'sp.addrankup'
  delrankup: 'sp.delrankup'
  dailyrewards: 'sp.dailyrewards'
  colorchat: 'sp.colorchat'
  colorsign: 'sp.colorsign'
  addcoins: 'sp.addcoins'
  removecoins: 'sp.removecoins'
  setcoins: 'sp.setcoins'
  removeteamcoins: 'sp.removeteam'
  vanish: 'sp.vanish'
  setspawn: 'sp.setspawn'
  delwarp: 'sp.delwarp'
  setwarp: 'sp.setwarp'
  chatclearuse: 'sp.cc.use'
  chatclearsee: 'sp.cc.see'
  unsign: 'sp.unsign'
  sign: 'sp.sign'
  signcolor: 'sp.signcolor'
  tphere: 'sp.tphere'
  tpa: 'sp.tpa'
  tp: 'sp.tp'
  tpother: 'sp.tpother'
  commandspy: 'sp.commandspy'
  invsee: 'sp.invsee'
  invclear: 'sp.invclear'
  heal: 'sp.heal'
  head: 'sp.head'
  headcooldown: 'sp.headcooldown'
  hat: 'sp.hat'
  hatblocks: 'sp.hatblocks'
  hatitems: 'sp.hatitems'
  globalmute: 'sp.globalmute'
  globalmutewrite: 'sp.globalmutewrite'
  gamemode: 'sp.gamemode'
  gamemodeother: 'sp.gamemodeother'
  fly: 'sp.fly'
  feed: 'sp.feed'
  enderchest: 'sp.enderchest'
  enderchestother: 'sp.enderchestother'
  sethome7: 'sp.sethome7'
  sethome8: 'sp.sethome8'
  sethome11: 'sp.sethome11'
  sethome13: 'sp.sethome13'
  sethome15: 'sp.sethome15'
  checkban: 'sp.checkban'
  checkmute: 'sp.checkmute'
  mute: 'sp.mute'
  muteexcept: 'sp.mute.except'
  tempmuteexcept: 'sp.mute.except'
  kick: 'sp.kick'
  ban: 'sp.ban'
  banexcept: 'sp.ban.except'
  tempban: 'sp.tempban'
  tempbanexcept: 'sp.tempban.except'
  tempmute: 'sp.tempmute'
  unmute: 'sp.unmute'
  unban: 'sp.unban'
  glow: 'sp.glow'